// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package repositories

import (
	"database/sql"
)

type Product struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	Price     int64        `json:"price"`
	UserID    int64        `json:"user_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type User struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	Email     string       `json:"email"`
	CreatedAt sql.NullTime `json:"created_at"`
}
