// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: product.sql

package repositories

import (
	"context"
	"database/sql"
)

const countProductsByUserID = `-- name: CountProductsByUserID :one
SELECT COUNT(*) FROM products
WHERE user_id = $1
`

func (q *Queries) CountProductsByUserID(ctx context.Context, db DBTX, userID int64) (int64, error) {
	row := db.QueryRowContext(ctx, countProductsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products(
    user_id,
    name,
    price
) VALUES (
    $1, $2, $3
) RETURNING id, name, price, user_id, created_at
`

type CreateProductParams struct {
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
	Price  int64  `json:"price"`
}

func (q *Queries) CreateProduct(ctx context.Context, db DBTX, arg CreateProductParams) (Product, error) {
	row := db.QueryRowContext(ctx, createProduct, arg.UserID, arg.Name, arg.Price)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, db DBTX, id int64) error {
	_, err := db.ExecContext(ctx, deleteProduct, id)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, price, user_id, created_at FROM products
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetProduct(ctx context.Context, db DBTX, id int64) (Product, error) {
	row := db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const getUserProducts = `-- name: GetUserProducts :many
SELECT id, name, price, user_id, created_at,
    EXISTS(
        SELECT 1
        FROM products AS pp
        WHERE pp.user_id = $1 AND pp.created_at < (
            SELECT created_at
            FROM products AS ppp
            WHERE ppp.user_id = $1 AND ppp.created_at < $2
            ORDER BY created_at ASC
            LIMIT 1
        )       
    )
FROM products AS p
WHERE p.user_id = $1 AND p.created_at < $2
ORDER BY p.created_at DESC
LIMIT $3
`

type GetUserProductsParams struct {
	UserID int64        `json:"user_id"`
	After  sql.NullTime `json:"after"`
	First  int32        `json:"first"`
}

type GetUserProductsRow struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	Price     int64        `json:"price"`
	UserID    int64        `json:"user_id"`
	CreatedAt sql.NullTime `json:"created_at"`
	Exists    bool         `json:"exists"`
}

func (q *Queries) GetUserProducts(ctx context.Context, db DBTX, arg GetUserProductsParams) ([]GetUserProductsRow, error) {
	rows, err := db.QueryContext(ctx, getUserProducts, arg.UserID, arg.After, arg.First)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserProductsRow
	for rows.Next() {
		var i GetUserProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.UserID,
			&i.CreatedAt,
			&i.Exists,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, price, user_id, created_at FROM products
WHERE user_id = $1
ORDER BY id
LIMIT $2
OFFSET $3
`

type ListProductsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProducts(ctx context.Context, db DBTX, arg ListProductsParams) ([]Product, error) {
	rows, err := db.QueryContext(ctx, listProducts, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET
    name = $2,
    price = $3
WHERE id = $1
RETURNING id, name, price, user_id, created_at
`

type UpdateProductParams struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Price int64  `json:"price"`
}

func (q *Queries) UpdateProduct(ctx context.Context, db DBTX, arg UpdateProductParams) (Product, error) {
	row := db.QueryRowContext(ctx, updateProduct, arg.ID, arg.Name, arg.Price)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}
