// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"time"
)

type NewProduct struct {
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
	Price  int    `json:"price"`
}

type NewUser struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type PageInfo struct {
	StartCursor string `json:"start_cursor"`
	EndCursor   string `json:"end_cursor"`
	HasNextPage bool   `json:"has_next_page"`
}

type Product struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Price     int       `json:"price"`
	UserID    int64     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	User      *User     `json:"user"`
}

type ProductEdge struct {
	Cursor string   `json:"cursor"`
	Node   *Product `json:"node"`
}

type Products struct {
	Edges    []*ProductEdge `json:"edges"`
	PageInfo *PageInfo      `json:"page_info"`
}

type UpdateProduct struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Price int    `json:"price"`
}

type URIID struct {
	ID int64 `json:"id"`
}

type User struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
	Products  *Products `json:"products"`
}

type UserProducts struct {
	UserID int64  `json:"user_id"`
	First  int    `json:"first"`
	After  string `json:"after"`
}
