name: Audit

on:
  push:
    branches: [master]
  pull_request: 
    branches: [master]

jobs:

    audit:
      runs-on: ubuntu-latest

      services:
        postgres:
          image: postgres:12
          env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: test
            POSTGRES_DB: go_restful_test
            POSTGRES_PORT: 5432
          ports:
            - 5432:5432
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

      steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify dependencies
        run: go mod verify

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run golint
        run: golint ./...

      - name: create environment file
        run: |
          touch app.env
          echo "${{ secrets.APP_ENV }}" > app.env

      - name: Install golang migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/
          which migrate

      - name: run postgres database migration
        run: migrate -database postgres://postgres:test@localhost:5432/go_restful_test?sslmode=disable -path db/postgres/schemas up

      - name: run tests
        run:
          go test ./servers/gin -v -cover
          go test ./db/postgres/repositories/ -v -cover